In [1]:
words = ["Rajesh", "likes", "machine", "learning"]

for position, word in enumerate(words):
    print(position, word)

0 Rajesh
1 likes
2 machine
3 learning


Creating Vocabolary for the words 

In [1]:
vocab = {
    "The": 0,
    "cat": 1,
    "drank": 2,
    "milk": 3
}

sentence = ["The", "cat", "drank", "milk"]

encoded = [vocab[word] for word in sentence]

print(encoded)  

[0, 1, 2, 3]


Using Embedding

In [2]:
embeddings = {
    "cat": [0.2, 0.8, -0.3],
    "dog": [0.3, 0.7, -0.2],
    "milk": [-0.6, 0.1, 0.9]
}

print(embeddings["cat"])

[0.2, 0.8, -0.3]


In [3]:
import numpy as np

cat = np.array([0.2, 0.8, -0.3])
dog = np.array([0.3, 0.7, -0.2])

distance = np.linalg.norm(cat - dog)

print(distance)

0.17320508075688776


In [4]:
import numpy as np

sentence = np.array([
    [0.1, 0.2, 0.3],      # The
    [0.2, 0.8, -0.3],     # cat
    [0.5, -0.2, 0.4],     # drank
    [-0.6, 0.1, 0.9]      # milk
])

print(sentence.shape)

(4, 3)


In [5]:
import numpy as np

words = ["cat", "dog", "milk"]

embeddings = {
    "cat": np.array([0.2, 0.8, -0.3]),
    "dog": np.array([0.3, 0.7, -0.2]),
    "milk": np.array([-0.6, 0.1, 0.9])
}

for word in words:
    print(f"{word}: {embeddings[word]}")

cat: [ 0.2  0.8 -0.3]
dog: [ 0.3  0.7 -0.2]
milk: [-0.6  0.1  0.9]


In [6]:
import numpy as np

rajesh = np.array([1, 0, 1])
loves = np.array([0, 1, 1])
machine = np.array([1, 1, 0])
learning = np.array([1, 1, 1])

In [7]:
sentence = np.array([
    rajesh,
    loves,
    machine,
    learning
])

print(sentence)


[[1 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


Giving attention to the words 

In [ ]:
The     = 5
cat     = 20
chased  = 35
the     = 5
mouse   = 35

Words need a representation that contains meaning.

cat
dog
lion
tiger should be closer

Using embedding

Dimension 1 = animal-ness
Dimension 2 = vehicle-ness

In [8]:
cat = [0.8, 0.2]
dog = [0.9, 0.1]
car = [0.1, 0.9]

Lets create 2d embedding

In [ ]:
The cat chased the mouse


In [9]:
cat   = [8,2]
chased= [5,5]
mouse = [7,3]