# Understanding Transformers

## Creating simple array and printing the index and value

In [1]:
words = ["Rajesh", "likes", "machine", "learning"]

for position, word in enumerate(words):
    print(position, word)

0 Rajesh
1 likes
2 machine
3 learning


## Creating Vocabolary for the words 

In [1]:
vocab = {
    "The": 0,
    "cat": 1,
    "drank": 2,
    "milk": 3
}

sentence = ["The", "cat", "drank", "milk"]

encoded = [vocab[word] for word in sentence]

print(encoded)  

[0, 1, 2, 3]


## Using Embedding

In [2]:
embeddings = {
    "cat": [0.2, 0.8, -0.3],
    "dog": [0.3, 0.7, -0.2],
    "milk": [-0.6, 0.1, 0.9]
}

print(embeddings["cat"])

[0.2, 0.8, -0.3]


### Calculate distance between embeddings

In [3]:
import numpy as np

cat = np.array([0.2, 0.8, -0.3])
dog = np.array([0.3, 0.7, -0.2])

distance = np.linalg.norm(cat - dog)

print(distance)

0.17320508075688776


In [4]:
import numpy as np

sentence = np.array([
    [0.1, 0.2, 0.3],      # The
    [0.2, 0.8, -0.3],     # cat
    [0.5, -0.2, 0.4],     # drank
    [-0.6, 0.1, 0.9]      # milk
])

print(sentence.shape)

(4, 3)


In [5]:
import numpy as np

words = ["cat", "dog", "milk"]

embeddings = {
    "cat": np.array([0.2, 0.8, -0.3]),
    "dog": np.array([0.3, 0.7, -0.2]),
    "milk": np.array([-0.6, 0.1, 0.9])
}

for word in words:
    print(f"{word}: {embeddings[word]}")

cat: [ 0.2  0.8 -0.3]
dog: [ 0.3  0.7 -0.2]
milk: [-0.6  0.1  0.9]


In [6]:
import numpy as np

rajesh = np.array([1, 0, 1])
loves = np.array([0, 1, 1])
machine = np.array([1, 1, 0])
learning = np.array([1, 1, 1])

In [7]:
sentence = np.array([
    rajesh,
    loves,
    machine,
    learning
])

print(sentence)


[[1 0 1]
 [0 1 1]
 [1 1 0]
 [1 1 1]]


## Giving attention to the words 

In [ ]:
The     = 5
cat     = 20
chased  = 35
the     = 5
mouse   = 35

Words need a representation that contains meaning.

cat
dog
lion
tiger should be closer

Using embedding

Dimension 1 = animal-ness
Dimension 2 = vehicle-ness

In [8]:
cat = [0.8, 0.2]
dog = [0.9, 0.1]
car = [0.1, 0.9]

## Lets create 2d embedding

In [ ]:
The cat chased the mouse


In [9]:
cat   = [8,2]
chased= [5,5]
mouse = [7,3]

In [ ]:
cat-mouse= [1,-1]
distance = sqrt(1^2 + (-1)^2) = sqrt(2) = 1.414

cat - chased = [3,-3]
distance = sqrt(3^2 + (-3)^2) = sqrt(18) = 4.242

TypeError: unsupported operand type(s) for -: 'list' and 'list'

Distance(cat, mouse)  = 1.41
Distance(cat, chased) = 4.24

## Dot product

In [ ]:
chased.cat =[5,5].[8,2] = 5*8 + 5*2 = 40 + 10 = 50
chased.mouse =[5,5].[7,3] = 5*7 + 5*3 = 35 + 15 = 50


In [11]:
import numpy as np

chased = np.array([5, 5])

words = {
    "cat": np.array([8, 2]),
    "mouse": np.array([7, 3]),
    "the": np.array([1, 0])
}

for word, vector in words.items():
    score = np.dot(chased, vector)
    print(word, score)

cat 50
mouse 50
the 5


## Attention weights must sum to 1.

In [14]:
import numpy as np

chased = np.array([5, 5])

words = {
    "cat": np.array([8, 2]),
    "mouse": np.array([7, 3]),
    "the": np.array([1, 0])
}

 
 
score = [np.dot(chased, vector) for vector in words.values()]
score
attention = np.exp(score) / np.sum(np.exp(score))
attention

 

array([5.00000000e-01, 5.00000000e-01, 1.43125929e-20])

In [16]:
Q = [2, 3]

K1 = [1, 1]
K2 = [4, 2]
K3 = [0, 5]

In [20]:
score = [np.dot(Q, K1), np.dot(Q, K2), np.dot(Q, K3)]
exp_score = np.exp(score)
attention = exp_score / np.sum(exp_score)
attention

array([3.31889066e-05, 2.68932495e-01, 7.31034316e-01])

In [21]:
import numpy as np

attention = np.array([0.2, 0.3, 0.5])

V = np.array([
    [1, 2],  # V1
    [3, 4],  # V2
    [5, 6]   # V3
])

output = attention @ V

print(output)

[3.6 4.6]


In [26]:
import numpy as np

words = ["Rajesh", "loves", "machine", "learning"]

embeddings = {
    "Rajesh":   np.array([4, 3]),
    "loves":    np.array([2, 1]),
    "machine":  np.array([2, 1]),
    "learning": np.array([4, 5])
}

query = embeddings["learning"]

scores = []

print("Dot Products")
print("-" * 20)

for word in words:
    score = np.dot(query, embeddings[word])
    scores.append(score)

    print(f"{word:10s} score = {score}")

scores = np.array(scores)

exp_scores = np.exp(scores - np.max(scores))
attention = exp_scores / exp_scores.sum()

print("\nAttention Weights")
print("-" * 20)

for word, weight in zip(words, attention):
    print(f"{word:10s} {weight:.4f}")

Dot Products
--------------------
Rajesh     score = 31
loves      score = 13
machine    score = 13
learning   score = 41

Attention Weights
--------------------
Rajesh     0.0000
loves      0.0000
machine    0.0000
learning   1.0000
